---
logging:
  level:
    org:
      springframework:
        web: INFO
    app:
      coronawarn: INFO

federation-gateway:
  base-url: ${FEDERATION_GATEWAY_BASE_URL:http://localhost:8005}
  connection-pool-size: 200
  ssl:
    key-store-path: ${FEDERATION_GATEWAY_KEYSTORE_PATH}
    key-store-pass: ${FEDERATION_GATEWAY_KEYSTORE_PASS}
    certificate-type: PKCS12

spring:
  main:
    web-application-type: NONE
  # Postgres configuration
  flyway:
    enabled: true
    locations: classpath:/db/migration, classpath:/db/specific/{vendor}
    password: ${POSTGRESQL_PASSWORD_FLYWAY:local_setup_flyway}
    user: ${POSTGRESQL_USER_FLYWAY:local_setup_flyway}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${POSTGRESQL_DATABASE}?ssl=true&sslmode=verify-full&sslrootcert=${SSL_POSTGRES_CERTIFICATE_PATH}&sslcert=${SSL_DISTRIBUTION_CERTIFICATE_PATH}&sslkey=${SSL_DISTRIBUTION_PRIVATE_KEY_PATH}
    username: ${POSTGRESQL_USER_DISTRIBUTION:local_setup_download}
    password: ${POSTGRESQL_PASSWORD_DISTRIBUTION:local_setup_download}

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
